import Head from 'next/head';
import Input from '@/components/Input';
import Card from '@/components/Card';
import Section from '@/components/Section';
import BottomButton from '@/components/BottomButton';
import InputSet from '@/components/InputSet';
import Dropdown from '@/components/Dropdown';
import useCardRegistration from '@/hooks/useCardRegistration';
import Spacing from '@/components/Spacing';
import CARD_COMPANIES from '@/constants/cardCompanies';
import If from '@/components/If';
import {css} from '@emotion/react';
import {useRouter} from 'next/router';
import PATHS from '@/constants/path';

export default function Home() {
  const {cvcHandler, passwordHandler, cardNumbersHandler, companyHandler, expirationHandler, ownerNameHandler} =
    useCardRegistration();

  const router = useRouter();

  const navigateToComplete = () => {
    const timestamp = Date.now();

    router.push({
      pathname: PATHS.COMPLETE_CARD_REGISTRATION,
      query: {
        cardNumber: cardNumbersHandler.values[0],
        company: companyHandler.selectedValue,
        ts: timestamp,
      },
    });
  };

  return (
    <>
      <Head>
        <title>페이먼츠</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        css={css`
          display: flex;
          flex-direction: column;
          align-items: center;

          gap: 32px;

          padding-top: 100px;
        `}
      >
        <Card
          expiration={expirationHandler.date}
          cardNumber={cardNumbersHandler.values}
          company={companyHandler.selectedValue}
          name={ownerNameHandler.name}
        />

        <If condition={cvcHandler.isValid}>
          <Section header={<Section.Header title="비밀번호를 입력해 주세요" description="앞의 2자리를 입력해주세요" />}>
            <InputSet
              labelText="비밀번호 앞 2자리"
              input={<Input placeholder="12" {...passwordHandler} type="password" inputMode="numeric" />}
            />
          </Section>
        </If>

        <If condition={ownerNameHandler.isValid}>
          <Section header={<Section.Header title="CVC 번호를 입력해 주세요" />}>
            <InputSet
              labelText="CVC"
              input={<Input placeholder="123" {...cvcHandler} type="number" inputMode="numeric" />}
            />
          </Section>
        </If>

        <If condition={expirationHandler.isValid}>
          <Section header={<Section.Header title="카드 소유자 이름을 입력해 주세요" />}>
            <InputSet
              labelText="소유자 이름"
              input={
                <Input
                  placeholder="PARK"
                  value={ownerNameHandler.name}
                  isError={ownerNameHandler.isError}
                  onChange={ownerNameHandler.handleName}
                />
              }
            />
          </Section>
        </If>

        <If condition={companyHandler.isValid}>
          <Section
            header={
              <Section.Header
                title="카드 유효기간을 입력해 주세요"
                description="월/년도(MMYY)를 순서대로 입력해 주세요."
              />
            }
          >
            <InputSet
              labelText="유효기간"
              input={
                <>
                  <Input
                    placeholder="MM"
                    isError={expirationHandler.errors.month}
                    onChange={expirationHandler.handleMonth}
                    value={expirationHandler.date.month}
                    onBlur={expirationHandler.fillZero}
                  />
                  <Input
                    placeholder="YY"
                    isError={expirationHandler.errors.year}
                    onChange={expirationHandler.handleYear}
                    value={expirationHandler.date.year}
                  />
                </>
              }
            />
          </Section>
        </If>

        <If condition={cardNumbersHandler.isValid}>
          <Section
            header={<Section.Header title="카드사를 선택해 주세요" description="현재 국내 카드사만 가능합니다." />}
          >
            <InputSet
              labelText="카드 번호"
              input={
                <Dropdown placeHolder="카드사를 선택해주세요" onChange={companyHandler.handleSelectedValue}>
                  {CARD_COMPANIES.map(({value, name}) => (
                    <Dropdown.Option key={value} value={value}>
                      {name}
                    </Dropdown.Option>
                  ))}
                </Dropdown>
              }
            />
          </Section>
        </If>

        <Section
          header={
            <Section.Header
              title="결제할 카드 번호를 입력해 주세요"
              description="본인 명의의 카드만 결제 가능합니다."
            />
          }
        >
          <InputSet
            labelText="카드 번호"
            input={
              <>
                <Input
                  placeholder="1234"
                  value={cardNumbersHandler.values[0]}
                  isError={cardNumbersHandler.errors[0]}
                  onChange={e => cardNumbersHandler.onChange(e, 0)}
                  onBlur={() => cardNumbersHandler.handleErrorCheck(0)}
                />
                <Input
                  placeholder="1234"
                  value={cardNumbersHandler.values[1]}
                  isError={cardNumbersHandler.errors[1]}
                  onChange={e => cardNumbersHandler.onChange(e, 1)}
                  onBlur={() => cardNumbersHandler.handleErrorCheck(1)}
                />
                <Input
                  placeholder="1234"
                  value={cardNumbersHandler.values[2]}
                  isError={cardNumbersHandler.errors[2]}
                  onChange={e => cardNumbersHandler.onChange(e, 2)}
                  onBlur={() => cardNumbersHandler.handleErrorCheck(2)}
                />
                <Input
                  placeholder="1234"
                  value={cardNumbersHandler.values[3]}
                  isError={cardNumbersHandler.errors[3]}
                  onChange={e => cardNumbersHandler.onChange(e, 3)}
                  onBlur={() => cardNumbersHandler.handleErrorCheck(3)}
                />
              </>
            }
          />
        </Section>
        <Spacing height={100} />
        <If condition={passwordHandler.isValid}>
          <BottomButton onClick={navigateToComplete}>확인</BottomButton>
        </If>
      </main>
    </>
  );
}
